apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-external
  name: node-exporter-external
  namespace: kubesphere-monitoring-system
subsets:
  - addresses:
      - ip: 192.168.1.3
    ports:
      - name: metrics
        port: 9100
        protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-external
  name: node-exporter-external
  namespace: kubesphere-monitoring-system
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  selector: null

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-external
    app.kubernetes.io/vendor: kubesphere
  name: node-exporter-external
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
    - interval: 1m
      metricRelabelings:
        - action: keep
          regex: node_(uname|network)_info|node_cpu_.+|node_memory_Mem.+_bytes|node_memory_SReclaimable_bytes|node_memory_Cached_bytes|node_memory_Buffers_bytes|node_network_(.+_bytes_total|up)|node_network_.+_errs_total|node_nf_conntrack_entries.*|node_disk_.+_completed_total|node_disk_.+_bytes_total|node_filesystem_files|node_filesystem_files_free|node_filesystem_avail_bytes|node_filesystem_size_bytes|node_filesystem_free_bytes|node_filesystem_readonly|node_load.+|node_timex_offset_seconds
          sourceLabels:
            - __name__
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - kubesphere-monitoring-system
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter-external
